### ISSUE TITLE
Plugin integration with NRE fails to return values

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/nile#107]
While extending Nile with plugins works well with CLI, one issue I've stumbled upon is returning values in the NRE. For simplicity, consider this plugin example:

```
# plugins/do_something.py

@click.command()
def do_something():
    click.echo("AHHHHHHHH")
    return 5
```

And let's say we have this script:

```
# scripts/do_something.py

def run(nre):
    x = nre.do_something()
    print(x)
```

Running the script will print `AHHHHHHHH` but the expected return value `5` is returned as `None`; therefore, the logic is being executed, but the values are not being returned.

**Comment by martriay** [comment]
Interesting. @franalgaba could you look into this?

**Comment by franalgaba** [comment]
Hi @andrew-fleming !

Glad to see you are using plugins. I reproduced the error you are having and diving into the NRE and how the plugins work there does not seem to be anything wrong.

Then, I looked at how click works internally for handling commands and... that's where the issue is. If you check the click documentation about [Command Return Values](https://click.palletsprojects.com/en/5.x/commands/?highlight=standalone_mode#command-return-values) you will see something like this:

>When a Click script is invoked as command line application (through [BaseCommand.main()](https://click.palletsprojects.com/en/5.x/api/#click.BaseCommand.main)) the return value is ignored unless the standalone_mode is disabled in which case it’s bubbled through.

So, how to solve the issue? When you are using the plugin in a programmatic way with the `NRE` you have to pass the `standalone_mode` argument like this in order to retrieve the return value from the click command:

```
# scripts/do_something.py

def run(nre):
    x = nre.do_something(standalone_mode=False)
    print(x)
```

Just tried it and it works as expected. Hope it helps :)

**Comment by andrew-fleming** [comment]
Haha amazing, works perfectly! I was trying to set `standalone_mode` in the actual plugin click method. I wonder if we can somehow abstract this out so users don't have to worry about including it; nevertheless, thank you @franalgaba! Very much appreciated :)

**Comment by martriay** [comment]
Caught wet abstract it?

**Comment by franalgaba** [comment]
Yes, definitely. It is possible to inject the parameter in the command call that happens underneath I think. It should be very straightforward. I will open a PR to handle this :)

**Comment by martriay** [comment]
Thanks!

**Comment by franalgaba** [comment]
> Thanks!

Just opened a PR with the fix :)
