### ISSUE TITLE
Adjust `declare` so only accounts can declare txs

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/nile#186]
As mentioned in the release notes: [https://github.com/starkware-libs/cairo-lang/releases](https://github.com/starkware-libs/cairo-lang/releases)

**Comment by martriay** [comment]
This also applies to `deploy`

**Comment by ericglau** [comment]
Is there currently a way to run `declare` with an account?

**Comment by martriay** [comment]
> Is there currently a way to run `declare` with an account?

Since [0.10 there's a special entrypoint](https://starkware.notion.site/StarkNet-0-10-0-4ac978234c384a30a195ce4070461257#5f3a4b78b6a34ffc8e457e452cdde0e4) for it because in (very close) future versions it will be mandatory. It corresponds to the [`__validate_declare__` method of Accounts](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/account/presets/Account.cairo#L76-L83).

**Comment by martriay** [comment]
I've come to realize `declare` is much simpler to implement than `deploy`, since the latter requires much more delicate handling around the failure/success of the deployment before registering the deployment locally.

Also, unlike the former `deploy` CLI method of `starknet`, this new deployment flow doesn't return the address of the newly deployed contract, since transactions return tx receipts, not the return value of the functions being invoked. Because of this, we would either need to read from the tx events log and retrieve the address, or compute it locally even before the tx goes through (which is doable since it's deterministic).

**Comment by martriay** [comment]
Live [UDC prototype on goerli](https://goerli.voyager.online/contract/0x1a8e53128903a412d86f33742d7f907f14ee8db566a14592cced70d52f96222#code).
