### ISSUE TITLE
Explain nile declare contract --alias my_contract

### ISSUE THREAD

**Issue by Shinwari536** [OpenZeppelin/nile#187]
`nile declare contract --alias my_contract`
What is the purpose of declaring a smart contract?

**Comment by martriay** [comment]
contracts in StarkNet [need to be declared](https://starknet.io/docs/hello_starknet/intro.html#declare-the-contract-on-the-starknet-testnet) before they're deployed. this is because onchain bytecode registration and contract instantiation are two different steps, avoiding code duplication in the chain's storage.

**Comment by martriay** [comment]
contracts in StarkNet [need to be declared](https://starknet.io/docs/hello_starknet/intro.html#declare-the-contract-on-the-starknet-testnet) before they're deployed. this is because onchain bytecode registration and contract instantiation are two different steps, avoiding code duplication in the chain's storage.
