### ISSUE TITLE
add warning about `deploy` deprecation

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#277]
@frangio suggested to add a warning to `nile deploy` about its upcoming deprecation, and that it will require an account soon.
once we fully replace the command with #276, calling the command this way should let the user know about the new flow

**Comment by ericnordelo** [comment]
I will add the warning in that 276.

A note on that: 276 will not fully replace the command but will add extra support for deployments through accounts.

To fully replace the command, I think we need at least to support starknet-devnet 0.3.5 (with predeployed UDC), because, until that, users need to manually deploy at least UDC for deploying through accounts.

Btw, the predeployed UDC in starknet-devnet is at address 0x25fcb74260022bd8ed7e8d542408941826b53345e478b8303d6f31744838a36, different from the one in goerli and mainnet.

**Comment by martriay** [comment]
Related: https://github.com/Shard-Labs/starknet-devnet/issues/326
