### ISSUE TITLE
End to end tests

### ISSUE THREAD

**Issue by fracek** [OpenZeppelin/nile#41]
We discussed both on Discord and in #40 about adding end to end tests. These tests would work as follows (let me know if I missed any step):

* Create a new virtual environment
* Install nile
* Install cairo using `nile install`
* Initialize a new repository with `nile init`
* Compile the project
* Run tests
* Setup an account for the user (note: requires a private key)
* Deploy smart contract
* Use the account to interact with the smart contract
* Read value back from smart contract

This series of commands tests everything available in nile except `nile node`, which could be tested by running all steps that involve a network interaction twice (with local node and with test network).

Since StarkNet does not have transaction fees for now we can generate a new private key every time we run the tests and then let the account rot (we can't destroy it anyway).

Any thoughts?

**Comment by martriay** [comment]
Sounds good! For the private key step we can just hardcode any key, even a dumb number like `123`.

The deployment step worries me because it depends on external factors (`starknet-devnet` on local, not to mention if we want to test public nets) but I guess that's fair since this is e2e not unit testing.

**Comment by fracek** [comment]
I mentioned a random key because if we deploy on the alpha goerli network we need to deploy a new account every time. Not needed for local nodes since they reset state every time we run the tests.

**Comment by TimNooren** [comment]
Really like the proposal :thumbsup: Some (general) questions/suggestions:

- I'm curious about the reason for having `nile install` to install `cairo-lang` and `starknet-devnet`, instead of including those in the installation requirements. The second option would avoid needing tests (that set up a virtual environment etc), but I'm sure there's a design decision that I'm not aware of:)

- `click` supports testing CLI commands using the [CliRunner](https://click.palletsprojects.com/en/8.0.x/api/#click.testing.CliRunner). Not 100% sure if the proposal is to run shell commands, but I think the CliRunner is at least a good first step.

- Regarding testing contract deployment and interactions: we could start with deploying to a local devnet, managed through `pytest` fixtures or something like docker-compose.

**Comment by martriay** [comment]
> I'm curious about the reason for having nile install to install cairo-lang and starknet-devnet, instead of including those in the installation requirements. The second option would avoid needing tests (that set up a virtual environment etc), but I'm sure there's a design decision that I'm not aware of:)

The reason is that back in the day installing Cairo wasn't as easy as `pip install cairo-lang`, so an utility for installing was useful -- moreover with a new Cairo version every two weeks. I still believe there's value in setting up a whole environment from scratch, although we have `nile init` for that.

agree with everything else

**Comment by fracek** [comment]
I think we have everything except we don't test interactions between node and nile. I think that's fine since we would be testing starknet-devnet more than nile itself.

**Comment by martriay** [comment]
Sounds good to me. Closing this!
