### ISSUE TITLE
Add `status` command

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/nile#98]
Add `observe` command (or some other name) that fetches the status of a transaction using an await/retry strategy. Ideally, this should be an optional flag for `send`, `invoke`, and `deploy`. See #90 for discussion and its implementation in `nile debug`.

**Comment by martriay** [comment]
Instead of having `nile debug` and `nile observe` doing basically the same, I think it's best to just rename `debug` to `status` and have a single command to serve both purposes: track the status of a transaction and display a human readable stack trace in case there's an error.

This sole functionality should be chained to `send` or `invoke` when passed a given flag. `--status` maybe?

**Comment by trevis-dev** [comment]
Well, Github auto release notes were not nice to me...

**Comment by martriay** [comment]
You're right. Fixed.

**Comment by trevis-dev** [comment]
Hello!
Can I try what I suggested or are you on it / would you rather have something else?

**Comment by andrew-fleming** [comment]
Hello, sir! Sorry for the delay. I don't believe anyone's working on this. There was some consideration regarding maybe having this as a plugin, but we'll have to update the logic anyway. Your suggestions sound really good to me—I think having flexibility here will be beneficial for users, but it's also easy to just use `debug` if preferred. I wonder what @martriay thinks.
